
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://jmirabel.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl:
destination: ../jmirabel.github.io/

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

##############
# Conversion #
##############
markdown: kramdown

#############
# HTML Head #
#############

lang: "en"
author: "Joseph Mirabel"
title: "Joseph Mirabel"
description: "Blog and website of John Smith, blogging mainly for tech. Opinions expressed are mine."
#keywords: "smith, jones, personal, jekyll, theme"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

typed:
  typeSpeed: 10
  startDelay: 200
  backSpeed: 0
  backDelay: 5000
  backspacing: false
  contentType: "'html'"

me-img: "/img/jetpacktocat.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

# Commented out in _layouts/post.html
email-share: True
fb-share: False
twitter-share: False
linkedin-share: True
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

#disqus-shortname: "panossakkos"

syntax-highlight: True

############
# Timeline #
############

# Moved to _data/events.yml

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "jmirabel@laas.fr"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/jmirabel"
  - title: "key" # keybase
    url: "https://keybase.io/jmirabel"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: jmirabel
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

emptyArray: []

# Sections shown in the index page

pages_list:
  About: 'about'
  Publications: 'highlight-publications'
  Timeline: 'timeline'
  Contact: 'contact'

menu-bar:
  About: '#about'
  Publications: '#highlight-publications'
  Thesis: 'publications/thesis.html'
  Timeline: '#timeline'
  Contact: '#contact'

pubcat:
  journal: "Journals"
  thesis: "Thesis"
  ic: "International Conferences"
  misc: "Miscelaneous"

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

kramdown:
  parse_block_html: false

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate

# Jekyll press (minifier)
jekyll-press:
  activate: false
  exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
